In [1]:
import pandas as pd
import re

In [2]:
pd.options.display.max_rows = 250

In [3]:
df = pd.read_csv('./data/countries_raw.csv', index_col=False)

In [4]:
df.columns

Index(['Staat oder Gebiet', 'Langform des Staatsnamens', 'Hauptstadt',
       'Einwohner2017', 'Flächein km²', 'Einw.pro km²', 'Flag­ge',
       'ISO-3-Kürzel', 'ISO-2-Kürzel', 'TLD', 'Englischer Name',
       'Lokaler Name'],
      dtype='object')

In [5]:
df.drop(['Staat oder Gebiet', 'Langform des Staatsnamens', 'Hauptstadt','Flächein km²', 'Einw.pro km²', 'Einw.pro km²', 'Flag­ge', 'TLD', 'Lokaler Name', ], axis=1, inplace=True)

In [6]:
df.columns

Index(['Einwohner2017', 'ISO-3-Kürzel', 'ISO-2-Kürzel', 'Englischer Name'], dtype='object')

In [7]:
df = df.rename(columns={"Englischer Name": "country", "ISO-3-Kürzel": "ISO3",
         'ISO-2-Kürzel': 'ISO2', 'Einwohner2017': 'population2017'})

In [8]:
df = df.loc[2:206]

In [9]:
# extracting numbers
df['population2017'] = df['population2017'].apply(
    lambda x: int(
        re.findall(
            r'\d+', str(x).replace('.', '')
        )[0]
    )
)

In [10]:
# set iso3 Kosovo
df.loc[df[df.country == 'Kosovo'].index,'ISO3'] = 'XKX'

In [11]:
# set iso2 namibia
df.loc[df[df.country == 'Namibia'].index,'ISO2'] = 'NA'

In [12]:
df[df.ISO3.isna()]

     population2017 ISO3 ISO2                              country
12           135000  NaN  NaN                  Republic of Artsakh
131          295000  NaN  NaN  Turkish Republic of Northern Cyprus
166         3500000  NaN  NaN                           Somaliland
183          555000  NaN  NaN                         Transnistria

In [13]:
df[df.ISO2.isna()]

     population2017 ISO3 ISO2                              country
12           135000  NaN  NaN                  Republic of Artsakh
131          295000  NaN  NaN  Turkish Republic of Northern Cyprus
166         3500000  NaN  NaN                           Somaliland
174           51000  SOS  NaN                        South Ossetia
183          555000  NaN  NaN                         Transnistria

In [14]:
# drop countries not in covid data
dropindex = df[df.ISO2.isna()].index
df.drop(index=dropindex, inplace=True)
df.reset_index(inplace=True, drop=True)

In [15]:
# cut ISO2
df['ISO2'] = df['ISO2'].apply(lambda x: str(x)[:2])

In [24]:
# removing alternative names 
df.country = df.country.apply(lambda x: x.split('oder')[0].replace("'", ''))
df.country = df.country.apply(lambda x: x.split(' (')[0].strip())

In [17]:
df

     population2017 ISO3 ISO2                                country
0          35500000  AFG   AF                            Afghanistan
1          93400000  EGY   EG                                  Egypt
2           2900000  ALB   AL                                Albania
3          42200000  DZA   DZ                                Algeria
4             80000  AND   AD                                Andorra
5          28600000  AGO   AO                                 Angola
6            100000  ATG   AG                    Antigua and Barbuda
7           1300000  GNQ   GQ                      Equatorial Guinea
8          44300000  ARG   AR                              Argentina
9           3000000  ARM   AM                                Armenia
10          9900000  AZE   AZ                             Azerbaijan
11        105000000  ETH   ET                               Ethiopia
12         24500000  AUS   AU                              Australia
13           400000  BHS   BS                                Bahamas
14          1500000  BHR   BH                                Bahrain
15        164700000  BGD   BD                             Bangladesh
16           300000  BRB   BB                               Barbados
17         11300000  BEL   BE                                Belgium
18           400000  BLZ   BZ                                 Belize
19         11200000  BEN   BJ                                  Benin
20           800000  BTN   BT                                 Bhutan
21         11100000  BOL   BO                                Bolivia
22          3500000  BIH   BA                 Bosnia and Herzegovina
23          2300000  BWA   BW                               Botswana
24        207900000  BRA   BR                                 Brazil
25           400000  BRN   BN                      Brunei Darussalam
26          7100000  BGR   BG                               Bulgaria
27         19600000  BFA   BF                           Burkina Faso
28         10400000  BDI   BI                                Burundi
29         18400000  CHL   CL                                  Chile
30         23600000  TWN   TW                                 Taiwan
31       1386800000  CHN   CN                                  China
32            11500  COK   CK                           Cook Islands
33          4900000  CRI   CR                             Costa Rica
34          5748769  DNK   DK                                Denmark
35         83100000  DEU   DE                                Germany
36            73000  DMA   DM                               Dominica
37         10700000  DOM   DO                     Dominican Republic
38          1000000  DJI   DJ                               Djibouti
39         16800000  ECU   EC                                Ecuador
40          6400000  SLV   SV                            El Salvador
41         24400000  CIV   CI                            Ivory Coast
42          5900000  ERI   ER                                Eritrea
43          1300000  EST   EE                                Estonia
44          1400000  SWZ   SZ                               Eswatini
45           900000  FJI   FJ                                   Fiji
46          5500000  FIN   FI                                Finland
47         65000000  FRA   FR                                 France
48          2000000  GAB   GA                                  Gabon
49          2100000  GMB   GM                            Gambia, the
50          3900000  GEO   GE                                Georgia
51         28800000  GHA   GH                                  Ghana
52           108000  GRD   GD                                Grenada
53         10700000  GRC   GR                                 Greece
54         16900000  GTM   GT                              Guatemala
55         11500000  GIN   GN                                 Guinea
56          1900000  GNB   GW                          Guinea-Bissau
57           800000  GUY   GY                                 Guyana
58         10600000  HTI   HT                                  Haiti
59          8900000  HND   HN                               Honduras
60       1352600000  IND   IN                                  India
61        264000000  IDN   ID                              Indonesia
62         39200000  IRQ   IQ                                   Iraq
63         80600000  IRN   IR                                   Iran
64          4800000  IRL   IE                                Ireland
65           350000  ISL   IS                                Iceland
66          8600000  ISR   IL                                 Israel
67         60500000  ITA   IT                                  Italy
68          2900000  JAM   JM                                Jamaica
69        126700000  JPN   JP                                  Japan
70         28300000  YEM   YE                                  Yemen
71          9700000  JOR   JO                                 Jordan
72         15900000  KHM   KH                               Cambodia
73         25000000  CMR   CM                               Cameroon
74         36700000  CAN   CA                                 Canada
75           517000  CPV   CV                             Cape Verde
76         18000000  KAZ   KZ                             Kazakhstan
77          2700000  QAT   QA                                  Qatar
78         49700000  KEN   KE                                  Kenya
79          6200000  KGZ   KG                             Kyrgyzstan
80           100000  KIR   KI                               Kiribati
81         49300000  COL   CO                               Colombia
82           800000  COM   KM                                Comoros
83         81500000  COD   CD      Congo, Democratic Republic of the
84          5000000  COG   CG                     Congo, Republic of
85         25500000  PRK   KP  Korea, Democratic Peoples Republic of
86         51400000  KOR   KR                     Korea, Republic of
87          1800000  XKX   XK                                 Kosovo
88          4100000  HRV   HR                                Croatia
89         11300000  CUB   CU                                   Cuba
90          4100000  KWT   KW                                 Kuwait
91          7000000  LAO   LA   Lao, People’s Democratic Republic of
92          2200000  LSO   LS                                Lesotho
93          1900000  LVA   LV                                 Latvia
94          6200000  LBN   LB                                Lebanon
95          4700000  LBR   LR                                Liberia
96          6400000  LBY   LY                                  Libya
97            40000  LIE   LI                          Liechtenstein
98          2800000  LTU   LT                              Lithuania
99           600000  LUX   LU                             Luxembourg
100        25500000  MDG   MG                             Madagascar
101        18600000  MWI   MW                                 Malawi
102        31600000  MYS   MY                               Malaysia
103          400000  MDV   MV                               Maldives
104        18900000  MLI   ML                                   Mali
105          438000  MLT   MT                                  Malta
106        35100000  MAR   MA                                Morocco
107           60000  MHL   MH                       Marshall Islands
108         4400000  MRT   MR                             Mauritania
109         1300000  MUS   MU                              Mauritius
110       129200000  MEX   MX                                 Mexico
111          107000  FSM   FM          Micronesia, Federal States of
112         3900000  MDA   MD                                Moldova
113           37800  MCO   MC                                 Monaco
114         3200000  MNG   MN                               Mongolia
115          600000  MNE   ME                             Montenegro
116        29700000  MOZ   MZ                             Mozambique
117        53400000  MMR   MM                                Myanmar
118         2500000  NAM   NA                                Namibia
119           10000  NRU   NR                                  Nauru
120        29400000  NPL   NP                                  Nepal
121         4800000  NZL   NZ                            New Zealand
122         6200000  NIC   NI                              Nicaragua
123        17100000  NLD   NL                            Netherlands
124        20600000  NER   NE                                  Niger
125       190900000  NGA   NG                                Nigeria
126            1229  NIU   NU                                   Niue
127         2100000  MKD   MK                        North Macedonia
128         5300000  NOR   NO                                 Norway
129         4700000  OMN   OM                                   Oman
130         8800000  AUT   AT                                Austria
131         1300000  TLS   TL                             East Timor
132       207600000  PAK   PK                               Pakistan
133         4900000  PSE   PS                              Palestine
134           21000  PLW   PW                                  Palau
135         4100000  PAN   PA                                 Panama
136         8300000  PNG   PG                       Papua New Guinea
137         6800000  PRY   PY                               Paraguay
138        31800000  PER   PE                                   Peru
139       105000000  PHL   PH                            Philippines
140        38400000  POL   PL                                 Poland
141        10300000  PRT   PT                               Portugal
142        12300000  RWA   RW                                 Rwanda
143        19600000  ROU   RO                                Romania
144       144500000  RUS   RU                                 Russia
145          700000  SLB   SB                        Solomon Islands
146        16400000  ZMB   ZM                                 Zambia
147          200000  WSM   WS                                  Samoa
148           32800  SMR   SM                             San Marino
149          200000  STP   ST                  São Tomé and Príncipe
150        32600000  SAU   SA                           Saudi Arabia
151        10100000  SWE   SE                                 Sweden
152         8500000  CHE   CH                            Switzerland
153        15800000  SEN   SN                                Senegal
154         7000000  SRB   RS                                 Serbia
155           90000  SYC   SC                             Seychelles
156         7600000  SLE   SL                           Sierra Leone
157        16600000  ZWE   ZW                               Zimbabwe
158         5700000  SGP   SG                              Singapore
159         5400000  SVK   SK                               Slovakia
160         2100000  SVN   SI                               Slovenia
161        14700000  SOM   SO                                Somalia
162        46600000  ESP   ES                                  Spain
163        21400000  LKA   LK                              Sri Lanka
164           50000  KNA   KN                  Saint Kitts and Nevis
165          200000  LCA   LC                            Saint Lucia
166          104000  VCT   VC       Saint Vincent and the Grenadines
167        56500000  ZAF   ZA                           South Africa
168        40600000  SDN   SD                                  Sudan
169        12600000  SSD   SS                            South Sudan
170          600000  SUR   SR                               Suriname
171        18300000  SYR   SY                                  Syria
172         8800000  TJK   TJ                             Tajikistan
173        57500000  TZA   TZ                               Tanzania
174        66100000  THA   TH                               Thailand
175         7800000  TGO   TG                                   Togo
176          123000  TON   TO                                  Tonga
177         1400000  TTO   TT                    Trinidad and Tobago
178        14900000  TCD   TD                                   Chad
179        10600000  CZE   CZ                         Czech Republic
180        11500000  TUN   TN                                Tunisia
181        83150000  TUR   TR                                 Turkey
182         5800000  TKM   TM                           Turkmenistan
183           10000  TUV   TV                                 Tuvalu
184        42800000  UGA   UG                                 Uganda
185        42300000  UKR   UA                                Ukraine
186         9800000  HUN   HU                                Hungary
187         3500000  URY   UY                                Uruguay
188        32600000  UZB   UZ                             Uzbekistan
189          300000  VUT   VU                                Vanuatu
190             829  VAT   VA                           Vatican City
191        31400000  VEN   VE                              Venezuela
192         9400000  ARE   AE                   United Arab Emirates
193       325400000  USA   US                          United States
194        66200000  GBR   GB                         United Kingdom
195        93700000  VNM   VN                                Vietnam
196         9500000  BLR   BY                                Belarus
197          600000  ESH   EH                         Western Sahara
198         4700000  CAF   CF               Central African Republic
199         1200000  CYP   CY                                 Cyprus

In [25]:
df.to_csv('./data/countries.csv', index=False)